import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { assertAdminPath, getAdminRoute, requireAdminSession } from "@/lib/auth";
import { withBasePath } from "@/lib/base-path";
import { customRequestStatuses } from "@/lib/custom-request-validation";
import { retryCustomRequestNotification, updateCustomRequest } from "../actions";

export const dynamic = "force-dynamic";
export default async function Page({params,searchParams}:{params:Promise<{adminPath:string;publicId:string}>;searchParams:Promise<{ok?:string;error?:string}>}) {
  await requireAdminSession(); const input = await params; assertAdminPath(input.adminPath);
  const query = await searchParams;
  const request = await prisma.customRequest.findUnique({where:{publicId:input.publicId},include:{attachments:true}});
  if (!request) notFound();
  const path = `${getAdminRoute()}/custom-requests`;
  const errors:Record<string,string> = {validation:"Перевірте статус, ціну й довжину полів.",quote:"Для пропозиції вкажіть погоджену ціну й термін.",save:"Не вдалося зберегти зміни. Спробуйте ще раз.",notification:"Не вдалося надіслати сповіщення. Спробуйте ще раз."};
  const notificationLabels = {pending:"Очікує",sent:"Надіслано",failed:"Помилка",skipped:"Не налаштовано"};
  return <main className="mx-auto max-w-[1000px] px-4 py-8"><a className="ghost-pill" href={withBasePath(path)}>До заявок</a><h1 className="my-6 text-3xl">Заявка {request.publicId}</h1>{query.error ? <p role="alert" className="status-message status-message--error">{errors[query.error] || "Не вдалося виконати дію."}</p> : null}{query.ok ? <p role="status" className="status-message status-message--ok">{query.ok === "saved" ? "Зміни збережено." : "Перевірте результат Telegram-сповіщення нижче."}</p> : null}<section className="glass-panel my-6 rounded-2xl p-5"><h2>{request.name} · {request.mode === "file" ? "Друк файлу" : "Моделювання"}</h2><p>Telegram: {request.telegramContact}</p>{request.phone ? <p>Телефон: {request.phone}</p> : null}<p className="whitespace-pre-wrap break-words">{request.description}</p><p>Кількість: {request.quantity} · бюджет: {request.budget === null ? "Не вказано" : `${request.budget} грн`}</p><p>Розміри: {request.dimensions || "Не вказано"}</p><p>Бажаний строк: {request.desiredDate || "Не вказано"}</p>{request.modelUrl ? <p><a className="underline break-all" href={request.modelUrl} target="_blank" rel="noreferrer">Модель або приклад (зовнішнє посилання)</a></p> : null}{request.productSlug ? <a className="underline" href={withBasePath(`/product/${request.productSlug}`)}>Базовий товар</a> : null}<h3 className="mt-4">Вкладення</h3>{request.attachments.length ? <ul>{request.attachments.map((file) => <li key={file.id}><a className="underline break-all" href={withBasePath(`${path}/${request.publicId}/attachments/${file.id}`)}>{file.originalName}</a> · {Math.ceil(file.size/1024)} КБ</li>)}</ul> : <p>Немає вкладень.</p>}</section><form action={updateCustomRequest} className="glass-panel grid gap-4 rounded-2xl p-5"><input type="hidden" name="publicId" value={request.publicId} /><label className="field-shell">Статус<select name="status" defaultValue={request.status}>{Object.entries(customRequestStatuses).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field-shell">Погоджена ціна, грн<input name="agreedPrice" type="number" min={0} max={10000000} step={1} defaultValue={request.agreedPrice ?? ""} /></label><label className="field-shell">Погоджений термін<input name="agreedLeadTime" maxLength={200} defaultValue={request.agreedLeadTime} /></label><label className="field-shell">Примітка власника<textarea name="ownerNote" rows={4} maxLength={3000} defaultValue={request.ownerNote} /></label><button className="accent-pill" type="submit">Зберегти зміни</button></form><section className="glass-panel mt-6 rounded-2xl p-5"><h2>Telegram: {notificationLabels[request.notificationStatus]}</h2>{request.notificationError ? <p>{request.notificationError}</p> : null}<form action={retryCustomRequestNotification}><input type="hidden" name="publicId" value={request.publicId}/><button className="ghost-pill mt-4" type="submit">Надіслати сповіщення повторно</button></form></section></main>;
}
