const APP_ROLES = ['admin', 'deanery', 'starosta', 'teacher', 'student'];
const PERSONAL_LABEL = 'Особисте';
const ADMIN_PANEL_ROLES = ['admin', 'deanery', 'starosta', 'teacher'];
const DEADLINE_ROLES = ['student', 'starosta', 'teacher'];
const JOURNAL_ROLES = ['admin', 'deanery', 'starosta', 'teacher', 'student'];
const JOURNAL_INSIGHT_ROLES = ['admin', 'deanery', 'starosta', 'teacher'];

const navConfig = {
  personalLabel: PERSONAL_LABEL,
  items: [
    // TODO: replace this temporary role/flag blend with the final centralized RBAC policy once it is exported outside app.js.
    {
      id: 'admin',
      label: 'Адмінка',
      href: '/admin',
      section: 'main',
      rolesAllowed: ADMIN_PANEL_ROLES,
      requiredFlags: ['canAccessAdminPanel'],
      matchMode: 'prefix',
    },
    {
      id: 'home',
      label: 'Головна',
      href: '/home',
      section: 'main',
      rolesAllowed: APP_ROLES,
      matchPaths: ['/home', '/my-day'],
    },
    {
      id: 'learning',
      label: 'Навчання',
      href: '/schedule',
      section: 'main',
      rolesAllowed: APP_ROLES,
      keepWhenActive: true,
      children: [
        {
          id: 'schedule',
          label: 'Розклад',
          href: '/schedule',
          section: 'main',
          rolesAllowed: APP_ROLES,
          matchPaths: ['/schedule'],
        },
        {
          id: 'journal',
          label: 'Журнал',
          href: '/journal',
          section: 'main',
          rolesAllowed: JOURNAL_ROLES,
          keepWhenActive: true,
          matchPaths: ['/journal'],
          children: [
            {
              id: 'journal-insights',
              label: 'Insights',
              href: '/journal/insights',
              section: 'main',
              rolesAllowed: JOURNAL_INSIGHT_ROLES,
              matchPaths: ['/journal/insights'],
            },
          ],
        },
        {
          id: 'teamwork',
          label: 'Teamwork',
          href: '/teamwork',
          section: 'main',
          rolesAllowed: APP_ROLES,
          matchPaths: ['/teamwork'],
        },
        {
          id: 'custom-deadlines',
          label: 'Дивні дедлайни',
          href: '/schedule?panel=deadlines',
          section: 'main',
          rolesAllowed: DEADLINE_ROLES,
          requiredFlags: ['canUseCustomDeadlines'],
          navAction: 'custom-deadlines',
          matchPaths: ['/schedule/custom-deadlines'],
        },
        {
          id: 'subjects',
          label: 'Предмети',
          href: '/subjects',
          section: 'main',
          rolesAllowed: APP_ROLES,
          matchPaths: ['/subjects'],
        },
        {
          id: 'teacher-hub',
          label: 'Teacher hub',
          href: '/teacher',
          section: 'main',
          rolesAllowed: ['teacher'],
          hidden: true,
          matchPaths: ['/teacher'],
        },
        {
          id: 'teacher-workspace',
          label: 'Teacher workspace',
          href: '/teacher/workspace',
          section: 'main',
          rolesAllowed: ['teacher'],
          hidden: true,
          matchPaths: ['/teacher/workspace'],
        },
        {
          id: 'teacher-subjects',
          label: 'Teacher subjects',
          href: '/teacher/subjects',
          section: 'main',
          rolesAllowed: ['teacher'],
          hidden: true,
          matchPaths: ['/teacher/subjects'],
        },
      ],
    },
    {
      id: 'personal',
      label: PERSONAL_LABEL,
      href: '/profile',
      section: 'main',
      rolesAllowed: APP_ROLES,
      keepWhenActive: true,
      children: [
        {
          id: 'profile',
          label: 'Профіль',
          href: '/profile',
          section: 'main',
          rolesAllowed: APP_ROLES,
          matchPaths: ['/profile'],
        },
        {
          id: 'messages',
          label: 'Повідомлення',
          href: '/schedule?panel=messages',
          section: 'main',
          rolesAllowed: APP_ROLES,
          requiredFlags: ['allowMessages'],
          navAction: 'messages',
          matchPaths: ['/messages'],
        },
        {
          id: 'theme',
          label: 'Зміна теми',
          href: '#theme-toggle',
          section: 'main',
          rolesAllowed: APP_ROLES,
          navAction: 'theme-toggle',
        },
      ],
    },
    {
      id: 'admin-pathways',
      label: 'Pathways',
      href: '/admin/pathways',
      section: 'main',
      rolesAllowed: ADMIN_PANEL_ROLES,
      requiredFlags: ['canManagePathways'],
      hidden: true,
      matchMode: 'prefix',
    },
    {
      id: 'deanery',
      label: 'Deanery',
      href: '/deanery',
      section: 'main',
      rolesAllowed: ['deanery'],
      hidden: true,
      matchPaths: ['/deanery'],
    },
  ],
};

module.exports = {
  APP_ROLES,
  navConfig,
};
